MyPersonalDiary/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPersonalDiary.Interfaces;

namespace MyPersonalDiary.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IRegistrationCodesService _registrationCodesService;

        public AdminController(IRegistrationCodesService registrationCodesService)
        {
            _registrationCodesService = registrationCodesService;
        }

        public async Task<IActionResult> Index()
        {
            var registrationCodes = await _registrationCodesService.GetRegistrationCodesAsync();
            return View(registrationCodes);
        }

        [HttpPost]
        public async Task<IActionResult> Create()
        {
            string newCode = await _registrationCodesService.CreateRegistrationCodeAsync();
            string newLink = Url.Action("Register", "Account", new { registrationCode = newCode }, "https");

            return Json(new { code = newCode, link = newLink });
        }

    }
}

MyPersonalDiary/Controllers/PostsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyPersonalDiary.Models;
using MyPersonalDiary.Interfaces;

namespace MyPersonalDiary.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private readonly IPostsService _postsService;
        private readonly IAccountService _accountService;

        public PostsController(IPostsService postsService, IAccountService accountService)
        {
            _postsService = postsService;
            _accountService = accountService;
        }

        // GET: Posts
        [Route("/")]
        public async Task<IActionResult> Index(int page = 1, string? searchTerm = null, DateTime? fromDate = null, DateTime? toDate = null)
        {
            User currentUser = await _accountService.GetCurrentUserAsync();
            List<Post> posts = await _postsService.GetPostsAsync(currentUser, searchTerm, fromDate, toDate);

            int pageSize = 5;
            var currentUrl = HttpContext.Request.Path + HttpContext.Request.QueryString;
            var paginatedPosts = new PaginatedList<Post>(posts, page, pageSize, currentUrl);
            ViewBag.PaginationString = paginatedPosts.GetPaginationString();

            return View(paginatedPosts);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post post, IFormFile? ImagePath)
        {
            List<string> errors = _postsService.ValidatePost(post);
            if (errors.Any())
            {
                ViewBag.ValidationErrors = errors;
                return View(post);
            }

            User currentUser = await _accountService.GetCurrentUserAsync();
            await _postsService.CreatePostAsync(currentUser, post, ImagePath);
            return RedirectToAction("Index", "Home");
        }

        // GET: Posts/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            User currentUser = await _accountService.GetCurrentUserAsync();
            var (post, errorMessage) = await _postsService.GetPostAsync(currentUser, id);
            if (errorMessage != null)
            {
                TempData["ErrorMessage"] = errorMessage;
                return View("Error");
            }

            return View(post);
        }

        // POST: Posts/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Post post, IFormFile? ImagePath)
        {
            User currentUser = await _accountService.GetCurrentUserAsync();
            var (existingPost, errorMessage) = await _postsService.GetPostAsync(currentUser, id);
            if (errorMessage != null)
            {
                TempData["ErrorMessage"] = errorMessage;
                return View("Error");
            }

            List<string> errors = _postsService.ValidatePost(post);
            if (errors.Any())
            {
                ViewBag.ValidationErrors = errors;
                return View(post);
            }

            await _postsService.EditPostAsync(existingPost, post, ImagePath);
            
            return RedirectToAction("Index", "Home");
        }

        // GET: Posts/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            User currentUser = await _accountService.GetCurrentUserAsync();
            var (post, errorMessage) = await _postsService.GetPostAsync(currentUser, id);
            if (errorMessage != null)
            {
                TempData["ErrorMessage"] = errorMessage;
                return View("Error");
            }

            return View(post);
        }

        // POST: Posts/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            User currentUser = await _accountService.GetCurrentUserAsync();
            var (post, errorMessage) = await _postsService.GetPostAsync(currentUser, id);
            if (errorMessage != null)
            {
                TempData["ErrorMessage"] = errorMessage;
                return View("Error");
            }

            await _postsService.DeletePostAsync(post);

            return RedirectToAction("Index", "Home");
        }
    }
}

MyPersonalDiary/Views/Shared/ErrorGuest.cshtml
@using MyPersonalDiary.ViewModels
@model ErrorViewModel
@{
    ViewData["Title"] = "Error";
    Layout = "~/Views/Shared/_LayoutGuest.cshtml";
}

<div class="text-center">
    <h1 class="text-danger">Помилка</h1>
    <h2 class="text-danger">@TempData["ErrorMessage"]</h2>
    <a asp-controller="Account" asp-action="Login">Уже є акаунт?</a>
</div>

MyPersonalDiary/Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<div class="text-center">
    <h1>404 - Сторінку не знайдено</h1>
    <a asp-controller="Home" asp-action="Index">Повернутись на головну сторінку</a>
</div>

MyPersonalDiary/Views/Shared/NotFoundGuest.cshtml
@{
    ViewData["Title"] = "Not Found";
}

<div class="text-center">
    <h1>404 - Сторінку не знайдено</h1>
    <a asp-controller="Account" asp-action="Login">На сторінку входу</a>
</div>

MyPersonalDiary/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyPersonalDiary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPersonalDiary.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Мій особистий щоденник</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posts" asp-action="Create">Додати запис</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Коди реєстрації</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <main role="main" id="main" class="container pb-3">
        <div class="mx-auto col-md-12 col-lg-10">
            @* Помилки *@
            @if (ViewBag.ValidationErrors != null)
            {
                <div class="alert alert-danger">
                    <h4>Помилки валідації:</h4>
                    <ul>
                        @foreach (var error in ViewBag.ValidationErrors)
                        {
                            <li>@error</li>
                        }
                    </ul>
                </div>
            }
            @if (ViewBag.Message != null)
            {
                <div class="alert alert-danger">
                    <h4>Повідомлення:</h4>
                    @ViewBag.Message
                </div>
            }
            @RenderBody()
        </div>
    </main>

    <footer class="text-muted">
        <div class="container text-center">
            &copy; 2024 - Мій особистий щоденник - <a asp-area="" asp-controller="Home" asp-action="Privacy">Політика конфіденційності</a>
            @if (SignInManager.IsSignedIn(User))
            {
                <span>|</span>
                <a asp-controller="Account" asp-action="Delete">Видалити акаунт</a>
            }
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyPersonalDiary/Views/Shared/_LayoutGuest.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyPersonalDiary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPersonalDiary.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
</head>
<body>
    <main role="main" id="main" class="d-flex justify-content-center align-items-center">
        <div class ="container mx-auto col-md-12 col-lg-10 d-flex justify-content-center align-items-center">
            <!-- Помилки -->
            @if (ViewBag.ValidationErrors != null)
            {
                <div class="alert alert-danger">
                    <h4>Помилки валідації:</h4>
                    <ul>
                        @foreach (var error in ViewBag.ValidationErrors)
                        {
                            <li>@error</li>
                        }
                    </ul>
                </div>
            }
            @if (ViewBag.Message != null)
            {
                <div class="alert alert-danger">
                    <h4>Повідомлення:</h4>
                    @ViewBag.Message
                </div>
            }
            @RenderBody()
        </div>
    </main>

    <footer class="text-muted">
        <div class="container text-center">
            &copy; 2024 - Мій особистий щоденник            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>